version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu
