version: '3.8'

services:
  python-demo:
    image: my-python-image:latest
    container_name: my-demo-container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
